services:
  - type: web
    name: Galebox-frontend
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/JorgePoma/Galebox/tree/master/Galebox-Backend 
    branch: master
    buildCommand: npm install && npm build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: galeboxdb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

  - type: web
    name: Galebox-backend
    env: node
    plan: free
    # Update the following line with your Remix GitHub repo
    repo: https://github.com/JorgePoma/Galebox/tree/master/Galebox
    branch: master
    buildCommand: npm install
    startCommand: ionic serve
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: Galebox-frontend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: galeboxdb
    plan: free # This database will expire 90 days after creation